-- MySQL Script generated by MySQL Workbench
-- Fri Jun 29 23:57:45 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mensajeria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mensajeria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mensajeria` DEFAULT CHARACTER SET utf8 ;
USE `mensajeria` ;

-- -----------------------------------------------------
-- Table `mensajeria`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mensajeria`.`persona` (
  `Cedula` VARCHAR(45) NOT NULL,
  `Nombre` VARCHAR(45) NULL DEFAULT NULL,
  `Apellido` VARCHAR(45) NULL DEFAULT NULL,
  `Usuario` VARCHAR(45) NULL DEFAULT NULL,
  `Contrasena` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`Cedula`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mensajeria`.`mensaje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mensajeria`.`mensaje` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `Remitente` VARCHAR(45) NULL DEFAULT NULL,
  `Destinatario` VARCHAR(45) NULL DEFAULT NULL,
  `Cuerpo` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `Fk_Remitente_idx` (`Remitente` ASC),
  INDEX `Fk_Destinatario_idx` (`Destinatario` ASC),
  CONSTRAINT `Fk_Destinatario`
    FOREIGN KEY (`Destinatario`)
    REFERENCES `mensajeria`.`persona` (`Cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Fk_Remitente`
    FOREIGN KEY (`Remitente`)
    REFERENCES `mensajeria`.`persona` (`Cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;

USE `mensajeria` ;

-- -----------------------------------------------------
-- procedure Incrementador
-- -----------------------------------------------------

DELIMITER $$
USE `mensajeria`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `Incrementador`(remite varchar(45), destino varchar(45), cuerpo varchar(100))
BEGIN
insert into mensaje (remitente,destinatario,cuerpo) values (remite,destino,cuerpo);
END$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
